### ISSUE TITLE
Add yy/mm/dd in date display format

### ISSUE THREAD

**Issue by Movisivi** [mydockfinder/mydockfinder-for-Win10-Win11#200]
The options provided do not match my Windows format and confuse me

**Comment by mydockfinder** [comment]
可以在lang文件夹里面的语言文件，比如English.ini，打开以后搜索[timeformat] 里面有修改方法




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mydockfinder/mydockfinder-for-Win10-Win11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月1日(星期三) 中午1:06
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[mydockfinder/mydockfinder-for-Win10-Win11] Add yy/mm/dd in date display format (#200)





 
The options provided do not match my Windows format and confuse me
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mydockfinder** [comment]
要在设置里面日期和时间的格式重新选择一次才会生效，不需要重新启动设置重新选择一次就可以了




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2021年9月1日(星期三) 晚上10:16
To: ***@***.***&gt;; 
Cc: "№じ ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Add yy/mm/dd in date display format (#200)






我改变了时间形式=世纪/毫升/日/日到时间形式=y/mm/dd dd，重新启动了，没有任何改变。你的程序要找的格式是什么？我以为它会跟随 Windows

—
你收到这个是因为你评论了。
直接回复此邮件，在 GitHub 上查看或取消订阅.
GitHub Mobile 上的分流通知监督办或机器人.

**Comment by Movisivi** [comment]
Still not working. Its just showing me the same entries. I want the the year/month/day to show next to the time.

**Comment by Movisivi** [comment]
Still not working. Its just showing me the same entries. I want the the year/month/date to show next to the time. Right now it should look like 21/09/02 12:05 but instead it says Thu Sep2 12:05

**Comment by Movisivi** [comment]
OK I figured it out. Idk if translation is shitty but I was supposed to edit **config.ini** not **lang.ini**. Changing the _datefmt_ to yy/MM/dd and restarting the program worked. Thanks

**Comment by mydockfinder** [comment]
不客气，好了就行了，有时候翻译不是很标准



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月3日(星期五) 凌晨1:15
收件人: ***@***.***&gt;; 
抄送: "№じ ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Add yy/mm/dd in date display format (#200)





 
OK I figured it out. Idk if translation is shitty but I was supposed to edit config.ini not lang.ini. Changing the datefmt to yy/MM/dd and restarting the program worked. Thanks
 
&mdash;
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
