### ISSUE TITLE
Add option to minimize windows to the application icon instead of the dock

### ISSUE THREAD

**Issue by Movisivi** [mydockfinder/mydockfinder-for-Win10-Win11#201]
Nexus Dock does this right but its styles suck. Please add this as  checkbox in Mydock > minimize window

**Comment by Movisivi** [comment]
So it turns out you can sorta do this if you disable "minimize the window to the dock" but then you lose that awesome genie minimize effect :(

**Comment by Movisivi** [comment]
Well nevermind. It looks like that option is already there. It must've been added with 5.9.9.99 cause I've never noticed it before. Cheers @mydockfinder

**Comment by mydockfinder** [comment]
5.9.9.99已经添加了最小化到应用图标



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月1日(星期三) 中午1:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [mydockfinder/mydockfinder-for-Win10-Win11] Add option to minimize windows to the application icon instead of the dock (#201)





 
So it turns out you can sorta do this if you disable "minimize the window to the dock" but then you lose that awesome genie minimize effect :(
 
&mdash;
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
